### PR TITLE
Update Dependabot Configuration

### PR DESCRIPTION
**Pull request by smaboshe**
Currently, we manually update our Terraform providers.

This commit configures Dependabot to create PRs for updates to Terraform providers.

### CODE REVIEW

**Comment by smaboshe** [comment]
I can imagine that we are deliberately not using Dependabot to update Terraform providers. I am hoping to use this PR and repo to run an experiment on whether there is an approach we can create that allows us to strike a balance between automatic and manual updates.

**Comment by OlamideOl1** [comment]
I think you can try this out, we don't use dependabots because some provider updates can break existing functionality. But it's probably fine if we stick to minor / patch updates.

**Review by OlamideOl1 — APPROVED** [review]

**Comment by smaboshe** [comment]
> I think you can try this out, we don't use dependabots because some provider updates can break existing functionality. But it's probably fine if we stick to minor / patch updates.

Good idea.

I'll merge this to begin an experiment to work on getting the configuration to work the way we need it to.

**Comment by smaboshe** [comment]
This was another bad merge that "Closed" instead of "Merged" the PR. It is successfully merged though.

**Pull request closed without merging**
